Portal/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from accounts.views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='index'),
    path('news/', include('news.urls')),
    path('accounts/', include('accounts.urls')),
    path('todo/', include('todolist.urls')),
    path('task/', include('tasksmanager.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.contrib.auth import views
from django.urls import path
from .views import SignUpView, profile, ChangePasswordView
from django.conf import settings
from django.conf.urls.static import static

app_name = 'accounts'


urlpatterns = [
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('signup/', SignUpView.as_view(), name='signup'),
    path('profile/', profile, name='users-profile'),
    path('password-change/', ChangePasswordView.as_view(), name='password_change'),
]

news/urls.py
from django.urls import path

from news import views
from news.views import NewsListView, NewsDetailView, NewsCreateView, NewsUpdateView


app_name = 'news'


urlpatterns = [
    path('', NewsListView.as_view(), name='news'),
    path('<int:pk>/', NewsDetailView.as_view(), name='detail_news'),
    path('<int:pk>/edit/', NewsUpdateView.as_view(), name='edit_news'),
    path('add/', NewsCreateView.as_view(), name='add_news'),
]

tasksmanager/urls.py
from django.urls import path
from tasksmanager.views import TaskListView, TaskDetailView, TaskUpdateView, TaskCreateView

app_name = 'tasksmanager'



urlpatterns = [
	path('', TaskListView.as_view(), name='list_tasks'),
	path('<int:pk>/', TaskDetailView.as_view(), name='detail_task'),
	path('<int:pk>/edit/', TaskUpdateView.as_view(), name='edit_task'),
	path('add/', TaskCreateView.as_view(), name='add_task'),
]

home/models.py
from django.contrib.auth.models import User
from django.db import models
from django.utils import timezone





class News(models.Model):
    title = models.CharField(max_length=200)
    publish = models.DateTimeField(default=timezone.now)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    body = models.TextField(null=True, blank=True)

    class Meta:
        ordering = ('-publish',)

    def __str__(self):
            return self.title

tasksmanager/models.py
from django.contrib.auth.models import User
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models
# from django.utils.translation import ugettext_lazy as _

# Create your models here.
from django.http import request


from django.contrib.auth.models import User
from django.urls import reverse


class Task(models.Model):

    CHOICES = (
        ('NEW', "Новая"),
        ('QUEUE', "В очереди"),
        ('WORK', "В работе"),
        ('DONE', "Выполнено"),
        ('CANCEL', "Отменённая"),
    )

    title = models.CharField(("Название"), max_length=50)
    description = models.TextField(("Описание"))
    author = models.ForeignKey(User, verbose_name=("Постановщик"), on_delete=models.CASCADE, related_name='tasks')
    executor = models.ForeignKey(User, on_delete=models.SET_NULL, blank=True, null=True, verbose_name=("Исполнитель"))
    status = models.CharField(("Статус "), choices=CHOICES, default='NEW', max_length=32)
    created_on = models.DateTimeField(("Дата создания"), auto_now_add=True)

    class Meta:
        ordering = ('-created_on',)

    @property
    def text_status(self):
        choices = dict(self.CHOICES)
        return choices[self.status]

    def get_absolute_url(self):
        return reverse('tasksmanager:list_tasks')


class Comment(models.Model):
    task = models.ForeignKey(Task, related_name="comments", on_delete=models.CASCADE)
    creator = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    text = models.TextField(('Комментарий'))
    created = models.DateTimeField(("Дата создания"), auto_now_add=True)

templates/taskmanager/_base_task.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link href="{% static 'css/tasksmanager.css' %}" rel="stylesheet">
</head>
<body>
    <div class="header_task">
        {% include 'taskmanager/_header_task.html' %}
    </div>

    <div class="wrapper">
        <div class="container-saidbar">
            {% include 'taskmanager/_sidebar_task.html' %}
        </div>

        <div class="content">
            {% block content %} {% endblock %}
        </div>
    </div>

{#    <div class="footer">#}
{#        {% include 'taskmanager/_footer_task.html' %}#}
{#    </div>#}


    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

templates/taskmanager/_footer_task.html
{% load static %}



<div class="container-footer">

    <h1>It's Footer</h1>

</div>

templates/taskmanager/_header_task.html
{% load static %}



<nav class="navbar navbar-expand-lg" style="padding-left: 43px;">
    <a href="{% url 'tasksmanager:list_tasks' %}">
        <div class="main-menu-logo">
            <img class=".navbar-brand" style="height: 24px;width: auto;" src="/media/logo.svg" alt="">
        </div>
    </a>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse ml-5" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'news:news' %}">Home</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'tasksmanager:list_tasks' %}">Задачи</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Документы</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Сотрудники</a>
      </li>


    </ul>
    <form class="form-inline my-2 my-lg-0">
      <div class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Меню
        </a>
        <div class="dropdown-menu"  style="font-size: 14px;" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Another action</a>
          <a class="dropdown-item" href="#">Another action</a>
        </div>
      </div>
      <input style="font-size: 12px;border-radius: 18px;" class="form-control mr-sm-2" type="search" placeholder="Найти" aria-label="Search">
    </form>
  </div>
</nav>

templates/taskmanager/_sidebar_task.html
{% load static %}


    <div class="">
        <div class="container-fluid">
        <div class="">
          <div class="navbar-container bg-light">
            <!-- Вертикальное меню -->
            <nav class="navbar navbar-expand-md">
              <a class="navbar-brand" href="#">Статус задач</a>
              <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
              <div style="margin: 0 auto;" class="collapse navbar-collapse" id="navbar">
                <!-- Пункты вертикального меню -->
                <ul class="navbar-nav">
                  <li class="nav-item">
                      <a class="nav-link" href="#">ВСЕ</a>
                  </li>
                  <li class="nav-item">
                      <a class="nav-link" href="#">ВХОДЯЩИЕ</a>
                  </li>
                  <li class="nav-item">
                      <a class="nav-link" href="#">ИСХОДЯЩИЕ</a>
                  </li>
                  <li class="nav-item">
                      <a class="nav-link" href="#">ИЗБРАННЫЕ</a>
                  </li>
                  <li class="nav-item">
                      <a class="nav-link" href="#">КОРЗИНА</a>
                  </li>
                  <li class="nav-item" style="margin-top: 150px;">
                      {% if user.is_authenticated %}
                          <div class="" style="text-align: center;">
                              <img class="rounded-circle account-img" src="{{ user.profile.avatar.url }} " style="cursor: pointer;width: 100px;height: 100px;" alt=""/>
                              <a href="{% url 'accounts:users-profile' %}" class="nav-link">{{user.username}}</a>
                              <a href="{% url 'accounts:logout' %}" class="btn btn-outline-success my-2 my-sm-0">Log out</a>
                          </div>
                      {% else %}
                          <div class="" style="text-align: center;">
                            <a href="{% url 'accounts:login' %}" class="btn btn-outline-success my-2 my-sm-0">Login</a>
                          </div>
                      {% endif %}
                  </li>
                </ul>
              </div>
            </nav>
          </div>
        </div>
      </div>
    </div>

templates/taskmanager/add_task.html
{% extends 'taskmanager/_base_task.html' %}
{% load crispy_forms_filters %}
{% load static %}


{% block content %}

    <div class="card" style="width: 60%;margin: 1% auto;">
        <div class="card-body">
            <h3 class="card-title">Add new task</h3><br>
            <form method="POST" class="">
                {% csrf_token %}
                {{ form|crispy }}
                <button type="submit" class="save btn btn-lg btn-outline-success">Save</button>
            </form>
        </div>
    </div>

{% endblock %}



{#                <div id="div_id_status" class="form-group">#}
{#                    <label for="id_status" class=" requiredField">#}
{#                        Status<span class="asteriskField">*</span>#}
{#                    </label>#}
{#                    <div>#}
{#                        <select name="status" class="select form-control" required="" id="id_status">#}
{#                            <option value="" selected="">---------</option>#}
{#                            {% for user in status_list %}#}
{#                                <option value="user">{{ user.1 }}</option>#}
{#                            {% endfor %}#}
{##}
{#                        </select>#}
{#                    </div>#}
{#                </div>#}
{##}
{#                <div id="div_id_title" class="form-group">#}
{#                    <label for="id_title" class=" requiredField">#}
{#                        Title#}
{#                        <span class="asteriskField">*</span>#}
{#                    </label>#}
{#                    <div>#}
{#                        <input type="text" name="title" maxlength="200" class="textinput textInput form-control" required="" id="id_title">#}
{#                    </div>#}
{#                </div>#}
{##}
{#                <div id="div_id_author" class="form-group">#}
{#                    <label for="id_author" class=" requiredField">#}
{#                        Author<span class="asteriskField">*</span>#}
{#                    </label>#}
{#                    <div>#}
{#                        <select name="author" class="select form-control" required="" id="id_author">#}
{#                            <option value="" selected="">---------</option>#}
{#                            {% for users in users_list %}#}
{#                                <option value="users">{{ users.username }}</option>#}
{#                            {% endfor %}#}
{#                        </select>#}
{#                    </div>#}
{#                </div>#}
{#                <div id="div_id_executor" class="form-group">#}
{#                    <label for="id_executor" class=" requiredField">#}
{#                        Executor<span class="asteriskField">*</span>#}
{#                    </label>#}
{#                    <div>#}
{#                        <select name="executor" class="select form-control" required="" id="id_executor">#}
{#                            <option value="" selected="">---------</option>#}
{#                            {% for users in users_list %}#}
{#                                <option value="users">{{ users.username }}</option>#}
{#                            {% endfor %}#}
{#                        </select>#}
{#                    </div>#}
{#                </div>#}
{#                <div id="div_id_body" class="form-group">#}
{#                    <label for="id_body" class="">Description</label>#}
{#                    <div>#}
{#                        <textarea name="body" cols="40" rows="10" class="textarea form-control" id="id_body"></textarea>#}
{#                    </div>#}
{#                </div>#}

templates/taskmanager/kablist.html
{#{% block kablist %}#}
{##}
{#    {% for users in users_list %}#}
{#        <p>#}
{#            {{ users.username }}#}
{#        </p>#}
{#    {% endfor %}#}
{##}
{#{% endblock kablist %}#}




<div id="div_id_author" class="form-group">
    <label for="id_author" class=" requiredField">
        Author<span class="asteriskField">*</span>
    </label>
    <div>
        <select name="author" class="select form-control" required="" id="id_author">
            <option value="" selected="">---------</option>
            <option value="">admin</option>
            {% for users in users_list %}
                <option value="users">{{ users.username }}</option>
            {% endfor %}

        </select>
    </div>
</div>

<div id="div_id_status" class="form-group">
    <label for="id_status" class=" requiredField">
        Status<span class="asteriskField">*</span>
    </label>
    <div>
        <select name="status" class="select form-control" required="" id="id_status">
            <option value="" selected="">---------</option>
            <option value="">status</option>
            {% for user in status_list %}
                <option value="user">{{ user.1 }}</option>
            {% endfor %}

        </select>
    </div>
</div>

{#<div class="">#}
{#    {{ status_list }}#}
{#    {% for user in status_list %}#}
{#        {{ user.1 }}#}
{#    {% endfor %}#}
{#</div>#}

templates/taskmanager/list_status.html
{% extends 'taskmanager/_base_task.html' %}
{% load static %}



<div class="columns has-background-link has-text-white is-centered" style="min-height: 101vh;">
	<div class="column is-half">
    	<h1 class="is-size-4 has-text-centered"> Добавить\Удалить статус </h1>
    	<form action="" method="post">
        	{% csrf_token %}
            <div class="field has-text-centered">
            	<label for="description" class="label has-text-white-bis">Введите статус</label>
            	<div class="control">
     	           <input type="text" id="description" class="input" placeholder="Какого рода у вас дела?"
                    	name="name" required>
            	</div>
            	<div class="field">
                	<button class="button is-primary" name="Add" type="submit">
                    	<span class="icon is-small">
                        	<i class="fa fa-plus"></i>
                    	</span>
                    	<span>Добавить статус</span>
                	</button>
                	<button class="button is-danger" name="Delete" formnovalidate="" type="submit">
                    	<span class="icon is-small">
           	             <i class="fa fa-trash-o"></i>
                    	</span>
	                    <span>Удалить статус</span>
                	</button>
            	</div>
            </div>

            <!--  cписок наших категорий -->
            <div class="list is-hoverable">
            	{% for status in statuses %}
            	<div class="list-item">
                	<label class="checkbox">
                    	<input type="checkbox" class="checkbox" name="check" value="{{status.id}}">
                    	<span class="complete-">{{ status.name }}</span>
                	</label>
            	</div>
            	{% endfor %}

        	</div>
    	</form>
	</div>
</div>

templates/taskmanager/list_tasks.html
{#{% load crispy_forms_filters %}#}
{% extends 'taskmanager/_base_task.html' %}
{% load static %}


{% block content %}
    <div class="container-main">
        <div class="btn-create-task m-3 mb-5">
            <a href="{% url 'tasksmanager:add_task' %}">
                <button type="button" class="btn btn-secondary">Создать задачу</button>
            </a>
            <button type="button" class="btn btn-secondary ml-4">Добавить cтатус</button>
        </div>

        <table class="table table-bordered" style="width: 98%;margin: 1rem;">
            <tbody>
                <thead>
                    <tr class="tr-common-item">
                      <td style="width: 40px;" class="td-item"><input type="checkbox"></td>
                      <th scope="col" style="width: 6%;">№</th>
                      <th scope="col" style="width: 11%;">Статус</th>
                      <th scope="col" style="width: 36%;">Название</th>
                      <th scope="col" style="width: 15%;">Постановщик</th>
                      <th scope="col" style="width: 15%;">Исполнитель</th>
                      <th scope="col" style="width: 15%;">Дата создания</th>
                    </tr>
                </thead>
                <tr>
                    <td colspan="99" style="padding: 3px;">
                        <div class="">
                            <input style="font-size: 12px;" class="form-control mr-sm-2" type="search" placeholder="Найти задачу" aria-label="Search">
                        </div>
                    </td>
                </tr>
                {% for task in object_list %}
                    <tr>
                      <td style="width: 40px;" class="td-item"><input type="checkbox"></td>
                      <th scope="row"> {{ task.pk }} </th>
                      <td> {{ task.status }} </td>
                      <td> <a href="#">{{ task.title }}</a> </td>
                      <td> {{ task.author }} </td>
                      <td> {{ task.executor }} </td>
                      <td> {{ task.created_on }} </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>

{% endblock %}