Portal/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from accounts.views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='index'),
    path('news/', include('news.urls')),
    path('accounts/', include('accounts.urls')),
    path('todo/', include('todolist.urls')),
    path('task/', include('tasksmanager.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

news/urls.py
from django.urls import path

from news import views
from news.views import NewsListView, NewsDetailView, NewsCreateView, NewsUpdateView


app_name = 'news'


urlpatterns = [
    path('', NewsListView.as_view(), name='news'),
    path('<int:pk>/', NewsDetailView.as_view(), name='detail_news'),
    path('<int:pk>/edit/', NewsUpdateView.as_view(), name='edit_news'),
    path('add/', NewsCreateView.as_view(), name='add_news'),
]

news/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse
from django.utils import timezone





class News(models.Model):
    title = models.CharField(max_length=200)
    publish = models.DateTimeField(default=timezone.now)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    img_author = models.ImageField(default='user.jpg', upload_to='profile_images/')
    body = models.TextField(null=True, blank=True)

    class Meta:
        ordering = ('-publish',)

    def get_absolute_url(self):
        return reverse('news:detail_news',
                       args=[str(self.id)])

    def __str__(self):
            return self.title

news/forms.py
from django import forms

from news.models import News


class NewsForm(forms.ModelForm):

    class Meta:
        model = News
        fields = ('title', 'body',)

news/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.shortcuts import render, redirect
from django.utils import timezone
from django.views.generic import ListView, DetailView, CreateView, UpdateView

from news.forms import NewsForm
from news.models import News


class NewsListView(ListView):
    queryset = News.objects.all()
    context_object_name = 'news'
    paginate_by = 3
    template_name = 'news/news.html'


class NewsDetailView(LoginRequiredMixin, DetailView):
    model = News
    template_name = 'news/detail_news.html'


class NewsUpdateView(LoginRequiredMixin, UpdateView):
    model = News
    template_name = 'news/edit_news.html'
    fields = ['title', 'body']


class NewsCreateView(LoginRequiredMixin, CreateView):
    model = News
    template_name = 'news/add_news.html'
    fields = ['title', 'author', 'body']


def news_list(request):
    object_list = News.objects.all()
    paginator = Paginator(object_list, 3)
    page = request.GET.get('page')

    try:
        news = paginator.page(page)
    except PageNotAnInteger:
        news = paginator.page(1)
    except EmptyPage:
        news = paginator.page(paginator.num_pages)

    return render(request,
                  'news/news.html', {
                      'page': page,
                      'news': news
                  })

templates/news/add_news.html
{% extends '_base.html' %}
{% load crispy_forms_filters %}
{% load static %}



{% block main %}

    <div class="main-list">
        <div class="card m-4">
            <div class="card-body">
                <h3 class="card-title">Add new news</h3><br>
                <form method="POST" class="">
                    {% csrf_token %}
                    {{ form|crispy }}
                    <button type="submit" class="save btn btn-lg btn-outline-success">Save</button>
                </form>
            </div>
        </div>
    </div>

{% endblock %}

templates/news/detail_news.html
{% extends '_base.html' %}
{% load static %}



{% block main %}

    <div class="main-wrap">
        <div class="main-list">
            <div class="card m-4">
                <div class="card-body">
                    <div class="post-entry">
                        <h5 class="card-title"><p>{{ news.title }}</p></h5>
                        <p  class="card-text">{{ news.body }}</p>
                        <div class="form-group" style="display: flex;margin-top: 1%;">
                            <img class="rounded-circle account-img" src="/media/{{ news.img_author }}" style="cursor: pointer;width: 50px;height: 50px;" alt="">
                            <div class="" style="margin-left: 2rem;">
                                <p style="font-style: italic;margin-bottom: 0;">Опубликовано: {{ news.publish|date:"d.m.Y H:i" }}</p>
                                <p style="font-style: italic;margin-bottom: 0;">Автор: {{news.author}}</p>
                            </div>
                        </div>
                        <a href="{% url 'news:edit_news' news.pk %}" class="btn float-sm-right btn-outline-success">Редактировать</a>
                    </div>
                </div>
            </div>
        </div>

        <div class="main-btn">
            <a href="{% url 'news:add_news' %}" class="btn btn-lg btn-outline-success">Добавить новости</a>
        </div>
    </div>

{%endblock %}

templates/news/edit_news.html
{% extends '_base.html' %}
{% load crispy_forms_filters %}
{% load static %}


{% block main %}

    <div class="main-list">
        <div class="card m-4">
            <div class="card-body">
                <div class="post-entry">
                    <h3 class="card-title">Edit post</h3>
                    <form action="" method="post">
                        {% csrf_token %}
                        {{ form|crispy }}
                        <button type="submit"  value="Update" class="save btn float-sm-right btn-outline-success">Save</button>
                    </form>
                </div>
            </div>
        </div>
    </div>


{% endblock %}

templates/news/news.html
{% extends '_base.html' %}
{% load static %}




{% block main %}

    <div class="main-wrap">
        <div class="main-list">
            {% for news in object_list %}
                <div class="card m-4">
                    <div class="card-body" style="padding: 1rem">
                        <h5 class="card-title"><p>{{ news.title }}</p></h5>
                        <p  class="card-text">{{ news.body|truncatewords:40 }}</p>
                        <div class="form-group" style="display: flex;margin-top: 1%;">
                            <img class="rounded-circle account-img" src="/media/{{ news.img_author }}" style="cursor: pointer;width: 50px;height: 50px;" alt="">
                            <div class="" style="margin-left: 2rem;">
                                <p style="font-style: italic;margin-bottom: 0;">Опубликовано: {{ news.publish|date:"d.m.Y H:i" }}</p>
                                <p style="font-style: italic;margin-bottom: 0;">Автор: {{news.author}}</p>
                            </div>
                        </div>
                        <p></p>
                        <a href="{% url 'news:detail_news' news.pk %}" class="btn btn-lg btn-outline-success">Подробнее</a>
                    </div>
                </div>
            {% endfor %}
        </div>

        <div class="main-btn">
            <a href="{% url 'news:add_news' %}" class="btn btn-lg btn-outline-success">Добавить новости</a>


        </div>

    </div>


    {% block pagination %}
        {% include 'news/pagination.html'  with page=page_obj %}
    {% endblock %}

{%endblock %}

templates/news/pagination.html
{% load static %}


<div class="pagination">
    <span class="step-links">
        {% if page.has_previous %}
            <a href="?page={{ page.previous_page_number }}">Previous</a>
        {% endif %}
        <span class="current">
            Page {{ page.number }} of {{ page.paginator.num_pages }}.
        </span>
        {% if page.has_next %}
            <a href="?page={{ page.next_page_number }}">Next</a>
        {% endif %}
    </span>
</div>