Portal/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from accounts.views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='index'),
    path('news/', include('news.urls')),
    path('accounts/', include('accounts.urls')),
    path('todo/', include('todolist.urls')),
    path('task/', include('tasksmanager.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.contrib.auth import views
from django.urls import path
from .views import SignUpView, profile, ChangePasswordView
from django.conf import settings
from django.conf.urls.static import static

app_name = 'accounts'


urlpatterns = [
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('signup/', SignUpView.as_view(), name='signup'),
    path('profile/', profile, name='users-profile'),
    path('password-change/', ChangePasswordView.as_view(), name='password_change'),
]

news/urls.py
from django.urls import path

from news import views
from news.views import NewsListView, NewsDetailView, NewsCreateView, NewsUpdateView


app_name = 'news'


urlpatterns = [
    path('', NewsListView.as_view(), name='news'),
    path('<int:pk>/', NewsDetailView.as_view(), name='detail_news'),
    path('<int:pk>/edit/', NewsUpdateView.as_view(), name='edit_news'),
    path('add/', NewsCreateView.as_view(), name='add_news'),
]

tasksmanager/urls.py
from django.urls import path
from tasksmanager.views import TaskListView, TaskDetailView, TaskUpdateView, TaskCreateView

app_name = 'tasksmanager'



urlpatterns = [
	path('', TaskListView.as_view(), name='list_tasks'),
	path('<int:pk>/', TaskDetailView.as_view(), name='detail_task'),
	path('<int:pk>/edit/', TaskUpdateView.as_view(), name='edit_task'),
	path('add/', TaskCreateView.as_view(), name='add_task'),
]

todolist/urls.py
from django.urls import re_path

from todolist.views import todo, category


app_name = 'todolist'


urlpatterns = [
	re_path(r'^todo/', todo, name="TodoList"),
	re_path(r'^category/', category, name="Category"),
]

templates/_base.html
{% load static %}

<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <title>Portal</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link href="{% static 'css/main.css' %}" rel="stylesheet">

</head>

<body>
    <div class="wrapper">
        <div class="header">
            {% include '_header.html' %}
        </div>
        <div class="content">
            <div class="sidebar">
                {% include '_sidebar.html' %}
            </div>
            <div class="main">
                {% block main %}
                {% endblock %}
            </div>
        </div>
    </div>

    <div class="footer">
        {% include '_footer.html' %}
    </div>
</body>
</html>

templates/_footer.html
{% load static %}


  <footer class="container-footer mr-4">
    <ul class="nav justify-content-end">
      <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">Home</a></li>
      <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">Contacts</a></li>
      <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">FAQs</a></li>
      <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">About</a></li>
    </ul>
    <p class="text-right text-muted  pb-2">© 2022 Company LEADS, Inc</p>
  </footer>

templates/_header.html
{% load static %}

<nav class="navbar navbar-expand-lg navbar-dark fixed-top bg-dark" style="padding-left: 43px;">
    <img src="https://419304.selcdn.ru/images.l406102/site_logo.png" alt="">

    <form class="form-inline ml-auto mt-2 mt-md-0">
        <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success my-2 my-sm-0 mr-4" type="submit">Search</button>
    </form>

</nav>

templates/_sidebar.html
{% load static %}

    <ul class="navbar-nav mr-auto navbar-dark bg-dark h-100">
      <li class="nav-item" style="margin-top: 74px;">
        <a class="nav-link" href="{% url 'index' %}">Home</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'news:news' %}">Blog</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'todolist:TodoList' %}">Todolist</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'tasksmanager:list_tasks' %}">TaskManager</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">About</a>
      </li>
      <li class="nav-item" style="margin-top: 150px;">
          {% if user.is_authenticated %}
              <div class="" style="text-align: center;">
                  <img class="rounded-circle account-img" src="{{ user.profile.avatar.url }} " style="cursor: pointer;width: 100px;height: 100px;" alt=""/>
                  <a href="{% url 'accounts:users-profile' %}" class="nav-link">{{user.username}}</a>
                  <a href="{% url 'accounts:logout' %}" class="btn btn-outline-success my-2 my-sm-0">Log out</a>
              </div>
          {% else %}
              <div class="" style="text-align: center;">
                  <a href="{% url 'accounts:login' %}" class="btn btn-outline-success my-2 my-sm-0">Login</a>
              </div>
          {% endif %}
      </li>
    </ul>

templates/index.html
{% extends '_base.html' %}
{% load static %}


{% block main %}

    <h1 class="heading-section" style="font-size: 46px;text-align: center;margin-top: 10%;">Welcome on my PORTAL !!</h1>

{% endblock %}