Portal/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from accounts.views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='index'),
    path('news/', include('news.urls')),
    path('accounts/', include('accounts.urls')),
    path('todo/', include('todolist.urls')),
    path('task/', include('tasksmanager.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.contrib.auth import views
from django.urls import path
from .views import SignUpView, profile, ChangePasswordView
from django.conf import settings
from django.conf.urls.static import static

app_name = 'accounts'


urlpatterns = [
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('signup/', SignUpView.as_view(), name='signup'),
    path('profile/', profile, name='users-profile'),
    path('password-change/', ChangePasswordView.as_view(), name='password_change'),
]

news/urls.py
from django.urls import path

from news import views
from news.views import NewsListView, NewsDetailView, NewsCreateView, NewsUpdateView


app_name = 'news'


urlpatterns = [
    path('', NewsListView.as_view(), name='news'),
    path('<int:pk>/', NewsDetailView.as_view(), name='detail_news'),
    path('<int:pk>/edit/', NewsUpdateView.as_view(), name='edit_news'),
    path('add/', NewsCreateView.as_view(), name='add_news'),
]

templates/profiles/change_password.html
{% extends "_base.html" %}



{% block main %}
    <div class="form-content my-3 p-3">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-lg-5">
                        <div class="card shadow-lg border-0 rounded-lg mt-0 mb-3">
                            <div class="card-header justify-content-center">
                              <h3 class="font-weight-light my-4 text-center">Change Your Password</h3>
                            </div>
                            {% if form.errors %}
                                <div class="alert alert-danger alert-dismissible" role="alert">
                                    <div id="form_errors">
                                        {% for key, value in form.errors.items %}
                                            <strong>{{ value }}</strong>
                                        {% endfor %}
                                    </div>
                                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>
                            {% endif %}

                            <div class="card-body">
                                <form method="POST">
                                    {% csrf_token %}
                                    <div class="form-row">
                                        <div class="col-md-10 offset-md-1">
                                            <div class="form-group">
                                                <label class="small mb-1" for="id_old_password">Old password</label>
                                                <input type="password" name="old_password" autocomplete="new-password"
                                                       class="form-control" required id="id_old_password"
                                                       placeholder="Enter Old Password"/>
                                                <span>
                                                </span>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="form-row">
                                        <div class="col-md-10 offset-md-1">
                                            <div class="form-group">
                                                <label class="small mb-1" for="id_new_password1">New password</label>
                                                <input type="password" name="new_password1" autocomplete="new-password"
                                                       class="form-control" required id="id_new_password1"
                                                       placeholder="Enter New Password"/>
                                                <span>
                                                </span>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="form-row">
                                        <div class="col-md-10 offset-md-1">
                                            <div class="form-group">
                                                <label class="small mb-1" for="id_new_password2">Confirm new password</label>
                                                <input type="password" name="new_password2" autocomplete="new-password"
                                                       required id="id_new_password2" class="form-control"
                                                       placeholder="Confirm New Password"/>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="form-row">
                                        <div class="col-md-10 offset-md-1">
                                            <div class="form-group mt-0 mb-1">
                                                <button type="submit" class="col-md-12 btn btn-dark" id="reset">Update Password</button>
                                            </div>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                </div>
            </div>
        </div>
    </div>
{% endblock main %}

templates/profiles/juste_password.html
{% extends "users/base.html" %}
{% block content %}






                              Change Your Password

                            {% if form.errors %}


                                        {% for key, value in form.errors.items %}
                                            {{ value }}
                                        {% endfor %}


                                        ×


                            {% endif %}



                                    {% csrf_token %}



                                                Old Password









                                                New Password









                                                New Password Confirmation







                                                Update Password










{% endblock content %}

templates/profiles/profile.html
{% extends "_base.html" %}
{% load static %}

{% block title %}Profile Page{% endblock title %}

{% block main %}

    <div class="form-content">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-lg-5">
                    <div class="card shadow-lg border-0 rounded-lg mt-0 pb-3">
                        <div class="card-header justify-content-center" style="width: 100%;">
                            <h3 class="font-weight-light my-4 text-center">Change Your Profile</h3>
                        </div>

                        <div class="row my-3" style="margin: 0 auto;">
                            <img class="rounded-circle account-img" src="{{ user.profile.avatar.url }} " style="cursor: pointer;" alt=""/>
                        </div>
                        {% if user_form.errors %}
                            <div class="alert alert-danger alert-dismissible" role="alert">
                                <div id="form_errors">
                                    {% for key, value in user_form.errors.items %}
                                        <strong>{{ value }}</strong>
                                    {% endfor %}
                                </div>
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                        {% endif %}
                        <div class="form-content" style="width: 76%;margin: 0 auto;">
                            <form method="post" enctype="multipart/form-data">
                                {% csrf_token %}
                                <div class="form-group">
                                    <label class="small mb-1">Username:</label>
                                    {{ user_form.username }}
                                    <label class="small mb-1">Email:</label>
                                    {{ user_form.email }}
                                </div>
                                <div class="form-group">
                                    <a href="{% url 'accounts:password_change' %}">Change Password</a>
                                    <hr>
                                    <label class="small mb-1">Change Avatar:</label>
                                    {{ profile_form.avatar }}
                                </div>
                                <label class="small mb-1">Bio:</label> {{ profile_form.bio }}
                                <br><br>
                                <div class="btn-save-and-reset" style="display: flex;justify-content: space-around;">
                                    <button type="submit" class="btn btn-lg btn-outline-success">Save Changes</button>
                                    <button type="reset" name="Reset" class="btn btn-lg btn-outline-success">Reset</button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock main %}